export const SET_WEATHER = 'SET_WEATHER';
export const WEATHER_REQUESTED = 'WEATHER_REQUESTED';
export const SET_LOCATION = 'SET_LOCATION';
export const CURRENT_LOCATION_REQUESTED = 'CURRENT_LOCATION_REQUESTED';
export const LOCATION_REQUESTED_BY_CITY = 'LOCATION_REQUESTED_BY_CITY';
export const FORECAST_REQUESTED = 'FORECAST_REQUESTED';
export const SET_API = 'SET_API';
